model = "gpt-5.4"
model_reasoning_effort = "xhigh"

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"

[mcp_servers.github]
url = "https://dbt.runlayer.com/api/v1/proxy/7e8a07e2-98ed-4c76-8edb-d8a68b55bccc/mcp"

[mcp_servers.github.tools.sub_issue_write]
approval_mode = "approve"

[mcp_servers.github.tools.issue_write]
approval_mode = "approve"

[mcp_servers.github.tools.add_issue_comment]
approval_mode = "approve"

[mcp_servers.github.tools.add_comment_to_pending_review]
approval_mode = "approve"

[mcp_servers.github.tools.pull_request_review_write]
approval_mode = "approve"

[mcp_servers.github.tools.add_reply_to_pull_request_comment]
approval_mode = "approve"

[mcp_servers.github.tools.fork_repository]
approval_mode = "approve"

[mcp_servers.github.tools.create_branch]
approval_mode = "approve"

[mcp_servers.github.tools.create_or_update_file]
approval_mode = "approve"

[mcp_servers.github.tools.create_pull_request]
approval_mode = "approve"

[mcp_servers.github.tools.update_pull_request_branch]
approval_mode = "approve"

[mcp_servers.github.tools.update_pull_request]
approval_mode = "approve"

[mcp_servers.slack]
url = "https://dbt.runlayer.com/api/v1/proxy/dcf3b868-a852-4758-97aa-024fb941a173/mcp"

[mcp_servers.dbt]
url = "https://dbt.runlayer.com/api/v1/proxy/404ba041-4eb4-4e29-a474-ae38e7899ac9/mcp"

[mcp_servers.grep]
url = "https://dbt.runlayer.com/api/v1/proxy/2af56970-3fbd-4f0b-9cd7-562e921c2c99/mcp"

[mcp_servers.salesforce]
url = "https://dbt.runlayer.com/api/v1/proxy/70b141cc-940c-4190-8da5-f9cd50d34923/mcp"

[mcp_servers.runlayer-docs]
url = "https://dbt.runlayer.com/api/v1/proxy/68a80158-1c82-4a97-b1aa-509703ad4b94/mcp"

[projects."/Users/dataders/Developer/internal-analytics"]
trust_level = "trusted"

[projects."/Users/dataders/Developer/fs"]
trust_level = "trusted"

[projects."/Users/dataders/Developer/scratch"]
trust_level = "trusted"

[projects."/Users/dataders/Developer/docs.getdbt.com"]
trust_level = "trusted"

[projects."/Users/dataders/Developer/fusion_issue_analysis"]
trust_level = "trusted"

[projects."/Users/dataders/Developer/dotfiles"]
trust_level = "trusted"
