version = "12"
default_toolchain = "beta-aarch64-apple-darwin"
profile = "default"

[overrides]
"/Users/dataders/Developer/fs" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.anders-docs-v2-wasm-v2" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.ci-duckdb-extended-rename-proper" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-config-get-rendered-clean" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-investigate-arithmetic" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-jj-mega-merge" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-macro-package" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-mega-merge" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-part-3.5-incremental" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-part-4-metadata" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-part-5-init" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-part-6-record-replay" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.clickhouse-part-9-materialized-view" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.codex-duckdb-quack-catalog" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.feat-wire-duckdb-extended-cdn" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.fix-jaffle-shop-clickhouse-compat" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.fix-selector-config-colon-value" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.fix-selectors-composite-expr-schema" = "beta-aarch64-apple-darwin"
