version = "12"
default_toolchain = "stable-aarch64-apple-darwin"
profile = "default"

[overrides]
"/Users/dataders/Developer/fs" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.9402-duckdb-catalogs-v2" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.9402-ducklake-v2-followup" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.agent-a168f9ba" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.cl-fix_defer_download_relation" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.codex-8044-goldies" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.codex-local-filesystem-catalog" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.dataders-hydration-progress-bars" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.dataders-hydration-progress-bars-more-emits" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.dataders-hydration-progress-bars-rebuild" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.dataders-jsonschema-selectors-profiles-cloud" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.dataders-packages-jsonschema-1619" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.dataders-regression-test-duckdb-cbr" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.dataders-regression-test-duckdb-column-binding-resolver" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.fix-1556-clone-ephemeral-log-message" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.fix-1570-snapshot-name-in-error" = "beta-aarch64-apple-darwin"
"/Users/dataders/Developer/fs.fix-duckdb-ducklake-is-ducklake" = "beta-aarch64-apple-darwin"
